let x=5;
let y=4;
console.log("add:",x+y);
console.log("sub:",x-y);
console.log("mul:",x*y);
console.log("div:",x/y);
console.log("mod:",x%y);
console.log("squ:",x**y);
console.log("inc:",x++);
console.log(++x);
console.log("dec:",y--);
console.log(--y);
console.log(100/50+x);